Application/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^vehicles/', include('vehicles.urls')),
    url(r'^products/', include('products.urls'))
]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/', logout, name='logout')
]

vehicles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<vehicle_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^add-vehicle$', views.add_vehicle, name="add_vehicle"),
    url(r'^(?P<vehicle_id>[0-9]+)/delete$', views.vehicle_delete, name='delete_vehicle'),
    url(r'^(?P<vehicle_id>[0-9]+)/vehicle-details$', views.vehicle_update, name='update_vehicle'),
    url(r'^ajax/validate_model/$', views.validate_model, name='validate_model'),
]

vehicles/models.py
from django.db import models


class Vehicle(models.Model):
    model = models.CharField(max_length=250)
    year = models.DateField()
    active = models.BooleanField(default=True);
    brand = models.ForeignKey('VehicleBrand', on_delete=models.CASCADE)

    def __str__(self):
        return self.model


class VehicleBrand(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

vehicles/forms.py
from django import forms
from vehicles.models import Vehicle


class VehicleForm(forms.ModelForm):

    class Meta:
        model = Vehicle
        exclude = ['active',]

vehicles/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator

from vehicles.forms import VehicleForm
from vehicles.models import Vehicle


def index(request):
    vehicles = Vehicle.objects

    query = request.GET.get("q")

    if query:
        vehicles = vehicles.filter(
            Q(model__icontains=query) |
            Q(brand__name__icontains=query) |
            Q(year__year__icontains=query)
        )

    context = {'vehicles': vehicles.all}

    return render(request, 'vehicles/index.html', context)


def detail(request, vehicle_id):
    vehicles = Vehicle.objects.all()
    vehicle_id = int(vehicle_id)

    form = VehicleForm(
        initial={
            'model': Vehicle.objects.get(id=vehicle_id).model,
            'year': Vehicle.objects.get(id=vehicle_id).year,
            'brand': Vehicle.objects.get(id=vehicle_id).brand
        }
    )

    if request.method == 'POST':
        form_post = VehicleForm(request.POST)

    #Temporary fix which deletes the extra vehicles created when adding
        if form_post.is_valid():
            form_post.auto_id = Vehicle.objects.get(id=vehicle_id).id
            profile = form_post.save()
            profile.pk = form_post.auto_id
            profile.save()

            vehicle = Vehicle.objects.get(id=vehicle_id+1)
            vehicle.active = False
            vehicle.save()

    context = {'vehicles': vehicles, 'vehicle_id': vehicle_id, "vehicle_form": form}
    return render(request, 'vehicles/vehicle-details.html', context)


def add_vehicle(request):
    form = VehicleForm()
    form_post = VehicleForm(request.POST)
    status = "none"
    return_string = 'vehicles/add-vehicle.html'

    if form_post.is_valid():
        status = "pass"
        profile = form_post.save(commit=False)
        profile.user = request.user
        profile.active = True
        profile.save()

    vehicles = Vehicle.objects.all()
    context = {'vehicles': vehicles, 'vehicle_form': form, "status": status}
    return render(request, return_string, context)


def validate_model(request):
    model = request.GET.get('model', None)

    data = {
        'is_taken': Vehicle.objects.filter(model__iexact=model).exists()
    }

    if data['is_taken']:
        data['error_message'] = 'A vehicle with this model already exists.'
    return JsonResponse(data)


def vehicle_delete(request, vehicle_id):
    vehicle = Vehicle.objects.get(id=vehicle_id)
    vehicle.active = False
    vehicle.save()
    return HttpResponseRedirect('/vehicles')


def vehicle_update(request, vehicle_id):
    instance = Vehicle.objects.get(id=vehicle_id)
    form = VehicleForm(request.POST or None, instance=instance)

    vehicles = Vehicle.objects.all

    if form.is_valid():
        form.save()
        return HttpResponse('/vehicles')

        return render(request, 'index.html', {'form': form})

vehicles/templates/vehicles/add-vehicle.html
{%  extends 'common/base.html' %}

{% block title %}Vehicles{% endblock %}

{% block javascript %}
  <script>
    $("#id_model").change(function () {
        console.log( $(this).val() );

      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-model-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
          }
        }
      });
    });
  </script>
{% endblock %}

{% block navigation %}{% include 'common/navigation.html' %}{% endblock %}

{% block main_content %}

    <div id="page-wrapper">

        <div class="panel panel-default" id="panel-main">

            <h1 class="page-header">Add New Vehicle</h1>

            {% load crispy_forms_tags %}
             <form id="add-form" method="post" data-validate-model-url="{% url 'validate_model' %}"> {% csrf_token %}
                 {{ vehicle_form|crispy }}
                 <div class="form-buttons">
                     <input class="btn btn-success" id="add-form-submit" type="submit">
                     <a class="btn btn-danger" id="go-back" href="/vehicles/">List of Vehicles</a>
                 </div>
             </form>

            <div class="alert alert-success alert-dismissable" style="display:{% if status == "pass" %}block{% else %}none{% endif %};">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    Vehicle Added Successfully
            </div>
            <div class="alert alert-danger alert-dismissable" style="display:{% if status == "fail" %}block{% else %}none{% endif %};">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    Vehicle was not added
            </div>

        </div>
    </div>
{% endblock %}

vehicles/templates/vehicles/index.html
{%  extends 'common/base.html' %}

{% block title %}Vehicles{% endblock %}

{% block navigation %}{% include 'common/navigation.html' %}{% endblock %}

{% block main_content %}

    <div id="page-wrapper">

        <form type="get" action="" style="margin: 0">

            <div class="form-group input-group">
                <input id="search_box" name="q" type="text" class="form-control" placeholder="Search Vehicles" value="{{ request.GET.q }}">
                <span class="input-group-btn">
                    <button id="btn-search" class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>

        <div class="panel panel-default" id="panel-main">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Vehicles</h1>
            </div>
        </div>

        {% if vehicles %}

        <div class="panel panel-default" id="content-table-container">
             <table class="table table-striped table-bordered table-hover" id="content-table">
                 <tr class="table-header">
    {#                 <td class="checkbox-column">Select</td>#}
                     <td>Model</td>
                     <td>Brand</td>
                     <td>Year</td>
                 </tr>

                 {% for vehicle in vehicles %}
                     {% if vehicle.active == True %}
                    <tr>
    {#                    <td class="checkbox-column"><input type="checkbox" id="item"></td>#}
                        <td><a href='/vehicles/{{vehicle.id}}'> {{vehicle.model}}</a></td>
                        <td>{{ vehicle.brand}}</td>
                        <td>{{ vehicle.year }}</td>
                    </tr>
                     {% endif %}
                {% endfor %}
             </table>
        </div>

        {% else %}
            <p>No vehicles found</p>

        {% endif %}

        </div>
    </div>
{% endblock %}

vehicles/templates/vehicles/vehicle-details.html
{%  extends 'common/base.html' %}

{% load static %}

{% block title %}Vehicles{% endblock %}

{% block navigation %}{% include 'common/navigation.html' %}{% endblock %}

{% block main_content %}

    <div id="page-wrapper">


        <div id="details-panel" class="panel panel-default">

            {% for vehicle in vehicles %}
                {% if vehicle.id == vehicle_id %}

                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">{{ vehicle.model }}</h1>
                        </div>
                    </div>

                    <img src="" alt="">
                    
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="vehicle-details">
                                <ul>
                                    <li class="vehicle-detail-category-title"><h3>Year</h3></li>
                                    <li class="vehicle-detail-content"><p>{{ vehicle.year }}</p></li>

                                    <li class="vehicle-detail-category-title"><h3>Brand</h3></li>
                                    <li class="vehicle-detail-content"><p>{{ vehicle.brand }}</p></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="form-buttons row">
                        <div class="col-lg-1">
                            <button id="edit-form-button" class="btn btn-success">Edit</button>
                        </div>
                        <div class="col-lg-2">
                            <a href="/vehicles/" class="btn btn-primary">Go Back</a>
                        </div>
                    </div>

                {% endif %}
            {% endfor %}
        </div>


        <div id="edit-details-panel" class="panel panel-default" >

            {% for vehicle in vehicles %}
                {% if vehicle.id == vehicle_id %}

                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Edit Details</h1>
                        </div>
                    </div>

                    {% load crispy_forms_tags %}

                    <form id="add-form" method="post"> {% csrf_token %}
                         {{ vehicle_form|crispy }}

                         <div class="form-buttons row">
                             <div class="col-lg-1">
                                 <input class="btn btn-success" type="submit" value="Save">
                             </div>
                             <div class="col-lg-2">
                                 <button id="details-button" class="btn btn-primary">Go Back</button>
                             </div>
                             <div class="col-lg-1">
                                 <a id="add-form-delete"href="delete" vehicle.id><i class="fa fa-trash"></i></a>
                             </div>
                         </div>
                    </form>
                {% endif %}
            {% endfor %}
        </div>

    </div>
{% endblock %}

{% block javascript %}<script src="{% static '/vehicles/js/edit-details.js'%}"></script>{% endblock %}